### ISSUE TITLE
accountsettings null

### ISSUE THREAD

**Issue by oshinjix3** [Azure-Samples/azure-batch-samples#289]
AccountSettings accountSettings = SampleHelpers.LoadAccountSettings();

I am not sure why the account is null when debugging when I have entered the correct settings from batch and storage in the accounts settttings.json.

I have copied the settings.json from the common file to HelloWorld file and it seems to not work as well.

When I run the c# helloworld solution it just timeouts.

**Comment by matthchr** [comment]
Does it work when not in debug mode for you?

**Comment by oshinjix3** [comment]
> Does it work when not in debug mode for you?

No, it does not. It gives me this error below


```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.Azure.Batch.Samples.HelloWorld.Program.Main(String[] args) in C:\Users\Admin\Desktop\azbatch\azure-batch-samples-master\CSharp\GettingStarted\01_HelloWorld\Program.cs:line 31

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
TimeoutException: Timed out waiting for resources after 00:10:00.

Inner Exception 2:
OperationCanceledException: The operation was canceled.
```
